name: CI git hub
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: clean project
        run: mvn clean
      - name: run all test
        run: mvn -Dspring.profiles.active=test test
      - name: create .jar and install
        run: mvn install